### ISSUE TITLE
Refactoring de la UI

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#112]
Organizar código

**Comment by Quimisagi** [comment]
Se modificó todo el código de la interfaz gráfico para hacerlo más legible y mantenible.

**Comment by Quimisagi** [comment]
Antes
![Capture](https://user-images.githubusercontent.com/26472514/94762180-98cf3600-036c-11eb-8cc7-db52bda06a22.PNG)

Después
![Capture2](https://user-images.githubusercontent.com/26472514/94762185-9a006300-036c-11eb-8bb1-f633a906026f.PNG)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
