### ISSUE TITLE
Refactoring Coro Melódico

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#113]

**Comment by Quimisagi** [comment]
Se reorganizó varios de los códigos para que sean más fáciles de leer y mantener.

**Comment by Quimisagi** [comment]
Antes
![Capture1](https://user-images.githubusercontent.com/26472514/94762216-b00e2380-036c-11eb-90e0-34347faae564.PNG)

Después
![Capture3](https://user-images.githubusercontent.com/26472514/94762217-b13f5080-036c-11eb-9a04-350d457a9b8b.PNG)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
