### ISSUE TITLE
Refactoring Cuenta-Ranas

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#114]
Se reescribió partes del código de cuenta ranas, y se cambió el nombre de las clases para que sea más legible y mantenible.

**Comment by Quimisagi** [comment]
Antes:
![Capture](https://user-images.githubusercontent.com/26472514/94762017-2e1dfa80-036c-11eb-8a4a-db23c25a973b.PNG)

Después:
![Capture2](https://user-images.githubusercontent.com/26472514/94762023-30805480-036c-11eb-90a6-881ca80a2ed3.PNG)

**Comment by Quimisagi** [comment]
![Uploading Capture4.PNG…]()

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
