### ISSUE TITLE
Instrucciones automáticas

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#115]
Hacer que las instrucciones aparezcan automáticamente cuando se abra un juego si no se ha registrado ningún puntaje hasta el momento. 

Actualmente únicamente implementado en coro y cuenta-ranas.

**Comment by DianaKToro** [comment]
It's not clear if the task has been completed. Please add description and evidence of results

**Comment by DianaKToro** [comment]
Instrucciones automáticas no aparece en los juegos come-insectos y colores

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
