### ISSUE TITLE
Actualizar sprites y arte de Cuenta Ranas

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#116]
Cambiar los prites de las ranas y el fondo.

Resultado:

![frame0001.png](https://images.zenhubusercontent.com/5bc1181733fe224966e8f79b/b6a0f0e0-8c71-4d73-be63-050b5827b185)![Arbusto.png](https://images.zenhubusercontent.com/5bc1181733fe224966e8f79b/5ed173e6-8671-4f95-b951-f336735a8b78)

**Comment by Quimisagi** [comment]
![Capture](https://user-images.githubusercontent.com/26472514/94383851-ce72e580-0106-11eb-9b68-69faf4b6ca9f.PNG)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
