### ISSUE TITLE
Cambiar forma de seleccionar modo de juego

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#118]
Quitar la opción de empezar el juego tocando el ícono del modo del juego y en su lugar añadir un botón que diga "Empezar juego".
Esto debido a que varios usuarios mayores no habían entendido cómo empezar el juego.

**Comment by Quimisagi** [comment]
Resultado:

![level1](https://user-images.githubusercontent.com/26472514/94762658-f6b04d80-036d-11eb-9ab6-3398f0f35ecb.png)

**Comment by DianaKToro** [comment]
Check. Change from done to closed.
