### ISSUE TITLE
Completación del protocolo

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#119]
Completar el protocolo para oficializar la investigación de este proyecto junto a la cooperación de la fundación Valle del Lilí.

Notas:
Sólamente la introducción, marco teórico, y especificación de equipos por ahora.

Resultado:
https://docs.google.com/document/d/1YQ8GZ6UmKFoHu4kJ-5JcTF4OLiEBKoUBt6fvr2Vf9ag/edit?usp=sharing

**Comment by Shinku24** [comment]
Revisado, por favor revisa las correcciones y comentarios que te deje en el documento, también revisa las pocas correcciones de palabras que hace google a lo mejor son más adecuadas al contexto
