### ISSUE TITLE
Crear prototipo juego de rompecabezas deslizante

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#128]
Crear prototipo para juego de rompecabezas deslizante

![image.png](https://images.zenhubusercontent.com/5bc1181733fe224966e8f79b/b68983f7-b896-494f-b8b7-bd14a1e1896a)

**Comment by Quimisagi** [comment]
![image](https://user-images.githubusercontent.com/26472514/98896239-828dbd00-2476-11eb-9c73-14289b10e13a.png)

**Comment by Shinku24** [comment]
Correcciones:
- Siempre dice "ganaste!" incluso cuando apenas se entra al minijuego

Sugerencias
- Al resolver el minijuego indicar con un mensaje
- No se que tan adecuado sea el nombre sliding cuando con un click se pueden mover los números
- Me parece que el color de fondo donde están los números (el cuadrado donde están los números) necesite mayor contraste con el fondo (puede que sea por la pantalla de mi celular)
- Ya que el botón "resolver" cambia el tablero debería llamarse distinto como "nuevo juego" ó "Mezclar" o algo así
