### ISSUE TITLE
Rompecabezas Deslizable: dividir imágenes

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#131]
Se deben poder dividir imagenes según el tamaño del rompecabezas (3x3, 4x4, 5x5)

Las fichas resultantes van divididas por un marco.

**Comment by Daniel0205** [comment]
llega un punto donde las fichas se quedan a mitad de camino
![WhatsApp Image 2020-12-09 at 4 13 16 PM](https://user-images.githubusercontent.com/24316482/101688081-7a0ab100-3a39-11eb-8f8a-da56311bdefe.jpeg)
