### ISSUE TITLE
Rompecabezas Deslizable: implementar la estructura general del juego y UI

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#133]
Implementar la estructura general de los minijuegos. Con esta estructura es posible pausar, reiniciar y abandonar el juego, ver las instrucciones, y escoger entre modos de juego (3x3, 4x4 y 5x5)

**Comment by Daniel0205** [comment]
Falta botón para devolverse cuando se selecciona la imagen.
Ready to be closed.
