### ISSUE TITLE
Crear nuevo prototipo

### ISSUE THREAD

**Issue by Quimisagi** [MCV-Univalle/Rivit#78]
Prototipo: cuentaranas

Presta atención a las ranas que entran y salen. Al final tendrás qué decir cuántas quedan dentro del arbusto.

![image.png](https://images.zenhubusercontent.com/5bc1181733fe224966e8f79b/ee27c519-2d3d-4d82-9278-3c01c65b05a3)

**Comment by Zixtor195** [comment]
very gud
