### ISSUE TITLE
Colores: Mejora en la mecanica de Drag

### ISSUE THREAD

**Issue by seibern** [MCV-Univalle/Rivit#94]
En el minijuego "Colores", el movimiento que hace el jugador (Drag) es bastante libre, por lo que se hará una mejora que permita que cuando el jugador se aproxime a una hoja, el jugador se ubique correctamente

**Comment by Shinku24** [comment]
![image](https://user-images.githubusercontent.com/24253574/96059739-60dbee80-0e54-11eb-8658-d8e521694895.png)

**Comment by Shinku24** [comment]
* Al hacer el drag con la rana se puede empujar el circulo, probablemente le pusiste una caja de colisión solo a ese circulo, porque no pasa con los otros elementos de la interfaz
* El puntaje queda negativo, esto debería pasar? y si la respuesta es sí hasta que valor negativo debería llegar
![image](https://user-images.githubusercontent.com/24253574/96060141-51a97080-0e55-11eb-807c-ec24e8dd903f.png)

**Comment by Shinku24** [comment]
* "cuando el jugador se aproxime a una hoja, el jugador se ubique correctamente": La rana se ubica correctamente en el centro de cada cuadro
* Al inicio parece que se debe conseguir dos correctas para sumar 1 a la puntuación, debe ser así?
* A partir de que la velocidad empieza a aumentar (probablemente ocurra siempre) hay un pequeño retraso para bajar la puntuación en caso de error
